version: "3.8"

services:
  db:
    image: mysql:latest
    container_name: mydb1
    networks:
      - lwnet
    volumes:
      - /data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=redhat
      - MYSQL_DATABASE=blogdb
      - MYSQL_USER=sumit
      - MYSQL_PASSWORD=redhat

  wp:
    image: wordpress:latest
    container_name: mywp1
    networks:
      - lwnet
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_HOST=mydb1
      - WORDPRESS_DB_USER=sumit
      - WORDPRESS_DB_PASSWORD=redhat
      - WORDPRESS_DB_NAME=blogdb

networks:
  lwnet:
    driver: bridge
